version: "2"

services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nextpage
    volumes:
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - MONGO_VOLUMES:/data/db
    ports: 
     - 27017:27017

  zookeeper:
    image: zookeeper:3.4
    mem_limit: 104857600
    container_name: zookeeper
    restart: unless-stopped
    ports:
      # exposing for debug reason
      - 2181:2181
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/datalog:/datalog"
      - "./zookeeper/zoo.cfg:/conf/zoo.cfg"     
  kafka:
    # 跟公司用同一個版本
    image: 'bitnami/kafka:2.1.1'
    # kafka 會用 hostname 來連線，會跟設定的 domain 不一樣
    # 使用 fluentd 時，也有遇過，連不同 server 時，需額外在 extra_hosts 設定該 hostname 對應的 ip
    # 這裡是開發環境，連本機，故把 hostname 設成 localhost 即可
    # issue: https://github.com/tulios/kafkajs/issues/479
    hostname: localhost
    container_name: kafka
    ports:
      # 方便從host call Kafka Connect 的Rest API (8083 port)
      - '8083:8083'
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - KAFKA_VOLUMES:/bitnami/kafka 
    depends_on:
      - zookeeper
volumes:
  MONGO_VOLUMES:
  KAFKA_VOLUMES:
